name: Android CI - Build and Sign Release APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Decode Keystore
      id: decode_keystore
      run: |
        mkdir -p ${{ github.workspace }}/keystores
        KEYSTORE_PATH="${{ github.workspace }}/keystores/release.jks"
        echo "Decoding keystore to $KEYSTORE_PATH"
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > $KEYSTORE_PATH
        echo "keystore_path=$KEYSTORE_PATH" >> $GITHUB_OUTPUT

    - name: Build and Sign Release APK
      env:
        # Pasa los secretos y la ruta del keystore como variables de entorno
        KEYSTORE_FILE_PATH: ${{ steps.decode_keystore.outputs.keystore_path }} # Ruta del keystore decodificado
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }} # Directamente del secreto
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}                 # Directamente del secreto
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}           # Directamente del secreto
      run: ./gradlew assembleRelease # O bundleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
        # Si es AAB: app/build/outputs/bundle/release/app-release.aab
